<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserProfileFormType;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;


class UserController extends AbstractController
{
    /**
     * @Route("/user/{userName}", name="app_userProfile")
     */
    public function profile($userName, Request $request, UserPasswordEncoderInterface $passwordEncoder)
    {
        $user = $this->getDoctrine()->getRepository(User::class)->findOneBy(['username' => $userName]);

        if ($user == null) {
            return $this->redirectToRoute('app_index');
        }

        $form = $this->createForm(UserProfileFormType::class, $user);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid())
        {
            $user = $form->getData();

            $fileSystem = new Filesystem();
            $oldAvatar = $user->getAvatar();

            /** @var UploadedFile $file */
            $file = $form['avatar']->getData();
            $password = $form['password_hash']->getData();

            if ($file)
            {
                if ($oldAvatar != null)
                {
                    $fileSystem->remove($this->getParameter('avatar_directory') . '/' . $oldAvatar);
                }
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

                // moves the file to the directory where avatars are stored
                $file->move(
                    $this->getParameter('avatar_directory'),
                    $fileName
                );

                $user->setAvatar($fileName);
                $this->addFlash('success', 'Profile picture changed successfully');
            }
            if ($password)
            {
                $currentPsw = $form['current_password']->getData();
                if ($passwordEncoder->isPasswordValid($user, $currentPsw))
                {
                    $user->setPassword($passwordEncoder->encodePassword($user, $password));
                    $this->addFlash('success', 'Password changed successfully');
                }
                else
                {
                    $this->addFlash('danger', 'To change password, enter correct current password');
                }
            }

            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
        }
        return $this->render('user/profile.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/admin/users", name="app_userList")
     */
    public function userList()
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'Unable to access this page!');

        $users = $this->getDoctrine()->getRepository(User::class)->findAll();
//        $x = $this->getDoctrine()->getRepository(User::class)->find(3);
//        $rolex = $x->getRoles();
//        dump($rolex);exit;
        return $this->render('user/userList.html.twig', [
        'users' => $users
        ]);
    }

    /**
 * @Route("/admin/user/{id}/delete", name="app_userDelete")
 */
    public function userDelete($id)
    {
        $manager = $this->getDoctrine()->getManager();
        $user = $manager->getRepository(User::class)->find($id);
        if ($user != null) {
            $manager->remove($user);
            $manager->flush();
            $this->addFlash('success', 'User "' . $user->getUsername() . '" successfully deleted');
        }
        return $this->redirectToRoute("app_userList");
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}
